name: Build OpenWrt Firmware

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Set up swap space
        run: |
          sudo fallocate -l 4G /swapfile
          sudo chmod 600 /swapfile
          sudo mkswap /swapfile
          sudo swapon /swapfile

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y build-essential clang flex bison g++ gawk \
            gcc-multilib g++-multilib gettext git libncurses-dev libssl-dev \
            python3-distutils rsync unzip zlib1g-dev file wget python3

      - name: Clone ImmortalWrt
        run: |
          git clone https://github.com/immortalwrt/immortalwrt.git openwrt
          cd openwrt
          ./scripts/feeds update -a
          ./scripts/feeds install -a

      - name: Copy custom config
        run: |
          cp .config openwrt/.config

      - name: Build firmware
        run: |
          cd openwrt
          make defconfig
          make download -j$(nproc)
          make -j$(nproc) V=s

      - name: Upload firmware
        uses: actions/upload-artifact@v3
        with:
          name: OpenWrt-CudyTR3000
          path: openwrt/bin
